// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: steammessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from steammessages.proto</summary>
public static partial class SteammessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for steammessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SteammessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNzdGVhbW1lc3NhZ2VzLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3Jp",
          "cHRvci5wcm90byL5AgoSQ01zZ1Byb3RvQnVmSGVhZGVyEhcKD2NsaWVudF9z",
          "dGVhbV9pZBgBIAEoBhIZChFjbGllbnRfc2Vzc2lvbl9pZBgCIAEoBRIVCg1z",
          "b3VyY2VfYXBwX2lkGAMgASgNEisKDWpvYl9pZF9zb3VyY2UYCiABKAY6FDE4",
          "NDQ2NzQ0MDczNzA5NTUxNjE1EisKDWpvYl9pZF90YXJnZXQYCyABKAY6FDE4",
          "NDQ2NzQ0MDczNzA5NTUxNjE1EhcKD3RhcmdldF9qb2JfbmFtZRgMIAEoCRIS",
          "CgdlcmVzdWx0GA0gASgFOgEyEhUKDWVycm9yX21lc3NhZ2UYDiABKAkSCgoC",
          "aXAYDyABKA0SRAoKZ2NfbXNnX3NyYxjIASABKA4yES5HQ1Byb3RvQnVmTXNn",
          "U3JjOhxHQ1Byb3RvQnVmTXNnU3JjX1Vuc3BlY2lmaWVkEhwKE2djX2Rpcl9p",
          "bmRleF9zb3VyY2UYyQEgASgNOgqAph2AAoimHYAIIncKO0NDaGluYUFncmVl",
          "bWVudFNlc3Npb25zX1N0YXJ0QWdyZWVtZW50U2Vzc2lvbkluR2FtZV9SZXF1",
          "ZXN0Eg0KBWFwcGlkGAEgASgNEg8KB3N0ZWFtaWQYAiABKAYSGAoQY2xpZW50",
          "X2lwYWRkcmVzcxgDIAEoCSJVCjxDQ2hpbmFBZ3JlZW1lbnRTZXNzaW9uc19T",
          "dGFydEFncmVlbWVudFNlc3Npb25JbkdhbWVfUmVzcG9uc2USFQoNYWdyZWVt",
          "ZW50X3VybBgBIAEoCSq2AQoQR0NQcm90b0J1Zk1zZ1NyYxIgChxHQ1Byb3Rv",
          "QnVmTXNnU3JjX1Vuc3BlY2lmaWVkEAASHwobR0NQcm90b0J1Zk1zZ1NyY19G",
          "cm9tU3lzdGVtEAESIAocR0NQcm90b0J1Zk1zZ1NyY19Gcm9tU3RlYW1JRBAC",
          "EhsKF0dDUHJvdG9CdWZNc2dTcmNfRnJvbUdDEAMSIAocR0NQcm90b0J1Zk1z",
          "Z1NyY19SZXBseVN5c3RlbRAEOjkKCWtleV9maWVsZBIdLmdvb2dsZS5wcm90",
          "b2J1Zi5GaWVsZE9wdGlvbnMY4NQDIAEoCDoFZmFsc2U6QQoSbXNncG9vbF9z",
          "b2Z0X2xpbWl0Eh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGODU",
          "AyABKAU6AjMyOkIKEm1zZ3Bvb2xfaGFyZF9saW1pdBIfLmdvb2dsZS5wcm90",
          "b2J1Zi5NZXNzYWdlT3B0aW9ucxjh1AMgASgFOgMzODQ="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GCProtoBufMsgSrc), }, new pb::Extension[] { SteammessagesExtensions.KeyField, SteammessagesExtensions.MsgpoolSoftLimit, SteammessagesExtensions.MsgpoolHardLimit }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgProtoBufHeader), global::CMsgProtoBufHeader.Parser, new[]{ "ClientSteamId", "ClientSessionId", "SourceAppId", "JobIdSource", "JobIdTarget", "TargetJobName", "Eresult", "ErrorMessage", "Ip", "GcMsgSrc", "GcDirIndexSource" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CChinaAgreementSessions_StartAgreementSessionInGame_Request), global::CChinaAgreementSessions_StartAgreementSessionInGame_Request.Parser, new[]{ "Appid", "Steamid", "ClientIpaddress" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CChinaAgreementSessions_StartAgreementSessionInGame_Response), global::CChinaAgreementSessions_StartAgreementSessionInGame_Response.Parser, new[]{ "AgreementUrl" }, null, null, null, null)
        }));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of steammessages.proto</summary>
public static partial class SteammessagesExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> KeyField =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(60000, pb::FieldCodec.ForBool(480000, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> MsgpoolSoftLimit =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(60000, pb::FieldCodec.ForInt32(480000, 32));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> MsgpoolHardLimit =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(60001, pb::FieldCodec.ForInt32(480008, 384));
}

#region Enums
public enum GCProtoBufMsgSrc {
  [pbr::OriginalName("GCProtoBufMsgSrc_Unspecified")] Unspecified = 0,
  [pbr::OriginalName("GCProtoBufMsgSrc_FromSystem")] FromSystem = 1,
  [pbr::OriginalName("GCProtoBufMsgSrc_FromSteamID")] FromSteamId = 2,
  [pbr::OriginalName("GCProtoBufMsgSrc_FromGC")] FromGc = 3,
  [pbr::OriginalName("GCProtoBufMsgSrc_ReplySystem")] ReplySystem = 4,
}

#endregion

#region Messages
public sealed partial class CMsgProtoBufHeader : pb::IMessage<CMsgProtoBufHeader>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgProtoBufHeader> _parser = new pb::MessageParser<CMsgProtoBufHeader>(() => new CMsgProtoBufHeader());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgProtoBufHeader> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgProtoBufHeader() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgProtoBufHeader(CMsgProtoBufHeader other) : this() {
    _hasBits0 = other._hasBits0;
    clientSteamId_ = other.clientSteamId_;
    clientSessionId_ = other.clientSessionId_;
    sourceAppId_ = other.sourceAppId_;
    jobIdSource_ = other.jobIdSource_;
    jobIdTarget_ = other.jobIdTarget_;
    targetJobName_ = other.targetJobName_;
    eresult_ = other.eresult_;
    errorMessage_ = other.errorMessage_;
    ip_ = other.ip_;
    gcMsgSrc_ = other.gcMsgSrc_;
    gcDirIndexSource_ = other.gcDirIndexSource_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgProtoBufHeader Clone() {
    return new CMsgProtoBufHeader(this);
  }

  /// <summary>Field number for the "client_steam_id" field.</summary>
  public const int ClientSteamIdFieldNumber = 1;
  private readonly static ulong ClientSteamIdDefaultValue = 0UL;

  private ulong clientSteamId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ClientSteamId {
    get { if ((_hasBits0 & 1) != 0) { return clientSteamId_; } else { return ClientSteamIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      clientSteamId_ = value;
    }
  }
  /// <summary>Gets whether the "client_steam_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasClientSteamId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "client_steam_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearClientSteamId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "client_session_id" field.</summary>
  public const int ClientSessionIdFieldNumber = 2;
  private readonly static int ClientSessionIdDefaultValue = 0;

  private int clientSessionId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ClientSessionId {
    get { if ((_hasBits0 & 2) != 0) { return clientSessionId_; } else { return ClientSessionIdDefaultValue; } }
    set {
      _hasBits0 |= 2;
      clientSessionId_ = value;
    }
  }
  /// <summary>Gets whether the "client_session_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasClientSessionId {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "client_session_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearClientSessionId() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "source_app_id" field.</summary>
  public const int SourceAppIdFieldNumber = 3;
  private readonly static uint SourceAppIdDefaultValue = 0;

  private uint sourceAppId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SourceAppId {
    get { if ((_hasBits0 & 4) != 0) { return sourceAppId_; } else { return SourceAppIdDefaultValue; } }
    set {
      _hasBits0 |= 4;
      sourceAppId_ = value;
    }
  }
  /// <summary>Gets whether the "source_app_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSourceAppId {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "source_app_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSourceAppId() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "job_id_source" field.</summary>
  public const int JobIdSourceFieldNumber = 10;
  private readonly static ulong JobIdSourceDefaultValue = 18446744073709551615UL;

  private ulong jobIdSource_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong JobIdSource {
    get { if ((_hasBits0 & 8) != 0) { return jobIdSource_; } else { return JobIdSourceDefaultValue; } }
    set {
      _hasBits0 |= 8;
      jobIdSource_ = value;
    }
  }
  /// <summary>Gets whether the "job_id_source" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasJobIdSource {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "job_id_source" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearJobIdSource() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "job_id_target" field.</summary>
  public const int JobIdTargetFieldNumber = 11;
  private readonly static ulong JobIdTargetDefaultValue = 18446744073709551615UL;

  private ulong jobIdTarget_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong JobIdTarget {
    get { if ((_hasBits0 & 16) != 0) { return jobIdTarget_; } else { return JobIdTargetDefaultValue; } }
    set {
      _hasBits0 |= 16;
      jobIdTarget_ = value;
    }
  }
  /// <summary>Gets whether the "job_id_target" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasJobIdTarget {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "job_id_target" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearJobIdTarget() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "target_job_name" field.</summary>
  public const int TargetJobNameFieldNumber = 12;
  private readonly static string TargetJobNameDefaultValue = "";

  private string targetJobName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TargetJobName {
    get { return targetJobName_ ?? TargetJobNameDefaultValue; }
    set {
      targetJobName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "target_job_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTargetJobName {
    get { return targetJobName_ != null; }
  }
  /// <summary>Clears the value of the "target_job_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTargetJobName() {
    targetJobName_ = null;
  }

  /// <summary>Field number for the "eresult" field.</summary>
  public const int EresultFieldNumber = 13;
  private readonly static int EresultDefaultValue = 2;

  private int eresult_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Eresult {
    get { if ((_hasBits0 & 32) != 0) { return eresult_; } else { return EresultDefaultValue; } }
    set {
      _hasBits0 |= 32;
      eresult_ = value;
    }
  }
  /// <summary>Gets whether the "eresult" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasEresult {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "eresult" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearEresult() {
    _hasBits0 &= ~32;
  }

  /// <summary>Field number for the "error_message" field.</summary>
  public const int ErrorMessageFieldNumber = 14;
  private readonly static string ErrorMessageDefaultValue = "";

  private string errorMessage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorMessage {
    get { return errorMessage_ ?? ErrorMessageDefaultValue; }
    set {
      errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "error_message" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasErrorMessage {
    get { return errorMessage_ != null; }
  }
  /// <summary>Clears the value of the "error_message" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearErrorMessage() {
    errorMessage_ = null;
  }

  /// <summary>Field number for the "ip" field.</summary>
  public const int IpFieldNumber = 15;
  private readonly static uint IpDefaultValue = 0;

  private uint ip_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Ip {
    get { if ((_hasBits0 & 64) != 0) { return ip_; } else { return IpDefaultValue; } }
    set {
      _hasBits0 |= 64;
      ip_ = value;
    }
  }
  /// <summary>Gets whether the "ip" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIp {
    get { return (_hasBits0 & 64) != 0; }
  }
  /// <summary>Clears the value of the "ip" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIp() {
    _hasBits0 &= ~64;
  }

  /// <summary>Field number for the "gc_msg_src" field.</summary>
  public const int GcMsgSrcFieldNumber = 200;
  private readonly static global::GCProtoBufMsgSrc GcMsgSrcDefaultValue = global::GCProtoBufMsgSrc.Unspecified;

  private global::GCProtoBufMsgSrc gcMsgSrc_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GCProtoBufMsgSrc GcMsgSrc {
    get { if ((_hasBits0 & 128) != 0) { return gcMsgSrc_; } else { return GcMsgSrcDefaultValue; } }
    set {
      _hasBits0 |= 128;
      gcMsgSrc_ = value;
    }
  }
  /// <summary>Gets whether the "gc_msg_src" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasGcMsgSrc {
    get { return (_hasBits0 & 128) != 0; }
  }
  /// <summary>Clears the value of the "gc_msg_src" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearGcMsgSrc() {
    _hasBits0 &= ~128;
  }

  /// <summary>Field number for the "gc_dir_index_source" field.</summary>
  public const int GcDirIndexSourceFieldNumber = 201;
  private readonly static uint GcDirIndexSourceDefaultValue = 0;

  private uint gcDirIndexSource_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GcDirIndexSource {
    get { if ((_hasBits0 & 256) != 0) { return gcDirIndexSource_; } else { return GcDirIndexSourceDefaultValue; } }
    set {
      _hasBits0 |= 256;
      gcDirIndexSource_ = value;
    }
  }
  /// <summary>Gets whether the "gc_dir_index_source" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasGcDirIndexSource {
    get { return (_hasBits0 & 256) != 0; }
  }
  /// <summary>Clears the value of the "gc_dir_index_source" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearGcDirIndexSource() {
    _hasBits0 &= ~256;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgProtoBufHeader);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgProtoBufHeader other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientSteamId != other.ClientSteamId) return false;
    if (ClientSessionId != other.ClientSessionId) return false;
    if (SourceAppId != other.SourceAppId) return false;
    if (JobIdSource != other.JobIdSource) return false;
    if (JobIdTarget != other.JobIdTarget) return false;
    if (TargetJobName != other.TargetJobName) return false;
    if (Eresult != other.Eresult) return false;
    if (ErrorMessage != other.ErrorMessage) return false;
    if (Ip != other.Ip) return false;
    if (GcMsgSrc != other.GcMsgSrc) return false;
    if (GcDirIndexSource != other.GcDirIndexSource) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasClientSteamId) hash ^= ClientSteamId.GetHashCode();
    if (HasClientSessionId) hash ^= ClientSessionId.GetHashCode();
    if (HasSourceAppId) hash ^= SourceAppId.GetHashCode();
    if (HasJobIdSource) hash ^= JobIdSource.GetHashCode();
    if (HasJobIdTarget) hash ^= JobIdTarget.GetHashCode();
    if (HasTargetJobName) hash ^= TargetJobName.GetHashCode();
    if (HasEresult) hash ^= Eresult.GetHashCode();
    if (HasErrorMessage) hash ^= ErrorMessage.GetHashCode();
    if (HasIp) hash ^= Ip.GetHashCode();
    if (HasGcMsgSrc) hash ^= GcMsgSrc.GetHashCode();
    if (HasGcDirIndexSource) hash ^= GcDirIndexSource.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasClientSteamId) {
      output.WriteRawTag(9);
      output.WriteFixed64(ClientSteamId);
    }
    if (HasClientSessionId) {
      output.WriteRawTag(16);
      output.WriteInt32(ClientSessionId);
    }
    if (HasSourceAppId) {
      output.WriteRawTag(24);
      output.WriteUInt32(SourceAppId);
    }
    if (HasJobIdSource) {
      output.WriteRawTag(81);
      output.WriteFixed64(JobIdSource);
    }
    if (HasJobIdTarget) {
      output.WriteRawTag(89);
      output.WriteFixed64(JobIdTarget);
    }
    if (HasTargetJobName) {
      output.WriteRawTag(98);
      output.WriteString(TargetJobName);
    }
    if (HasEresult) {
      output.WriteRawTag(104);
      output.WriteInt32(Eresult);
    }
    if (HasErrorMessage) {
      output.WriteRawTag(114);
      output.WriteString(ErrorMessage);
    }
    if (HasIp) {
      output.WriteRawTag(120);
      output.WriteUInt32(Ip);
    }
    if (HasGcMsgSrc) {
      output.WriteRawTag(192, 12);
      output.WriteEnum((int) GcMsgSrc);
    }
    if (HasGcDirIndexSource) {
      output.WriteRawTag(200, 12);
      output.WriteUInt32(GcDirIndexSource);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasClientSteamId) {
      output.WriteRawTag(9);
      output.WriteFixed64(ClientSteamId);
    }
    if (HasClientSessionId) {
      output.WriteRawTag(16);
      output.WriteInt32(ClientSessionId);
    }
    if (HasSourceAppId) {
      output.WriteRawTag(24);
      output.WriteUInt32(SourceAppId);
    }
    if (HasJobIdSource) {
      output.WriteRawTag(81);
      output.WriteFixed64(JobIdSource);
    }
    if (HasJobIdTarget) {
      output.WriteRawTag(89);
      output.WriteFixed64(JobIdTarget);
    }
    if (HasTargetJobName) {
      output.WriteRawTag(98);
      output.WriteString(TargetJobName);
    }
    if (HasEresult) {
      output.WriteRawTag(104);
      output.WriteInt32(Eresult);
    }
    if (HasErrorMessage) {
      output.WriteRawTag(114);
      output.WriteString(ErrorMessage);
    }
    if (HasIp) {
      output.WriteRawTag(120);
      output.WriteUInt32(Ip);
    }
    if (HasGcMsgSrc) {
      output.WriteRawTag(192, 12);
      output.WriteEnum((int) GcMsgSrc);
    }
    if (HasGcDirIndexSource) {
      output.WriteRawTag(200, 12);
      output.WriteUInt32(GcDirIndexSource);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasClientSteamId) {
      size += 1 + 8;
    }
    if (HasClientSessionId) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientSessionId);
    }
    if (HasSourceAppId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SourceAppId);
    }
    if (HasJobIdSource) {
      size += 1 + 8;
    }
    if (HasJobIdTarget) {
      size += 1 + 8;
    }
    if (HasTargetJobName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetJobName);
    }
    if (HasEresult) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Eresult);
    }
    if (HasErrorMessage) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
    }
    if (HasIp) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Ip);
    }
    if (HasGcMsgSrc) {
      size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) GcMsgSrc);
    }
    if (HasGcDirIndexSource) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(GcDirIndexSource);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgProtoBufHeader other) {
    if (other == null) {
      return;
    }
    if (other.HasClientSteamId) {
      ClientSteamId = other.ClientSteamId;
    }
    if (other.HasClientSessionId) {
      ClientSessionId = other.ClientSessionId;
    }
    if (other.HasSourceAppId) {
      SourceAppId = other.SourceAppId;
    }
    if (other.HasJobIdSource) {
      JobIdSource = other.JobIdSource;
    }
    if (other.HasJobIdTarget) {
      JobIdTarget = other.JobIdTarget;
    }
    if (other.HasTargetJobName) {
      TargetJobName = other.TargetJobName;
    }
    if (other.HasEresult) {
      Eresult = other.Eresult;
    }
    if (other.HasErrorMessage) {
      ErrorMessage = other.ErrorMessage;
    }
    if (other.HasIp) {
      Ip = other.Ip;
    }
    if (other.HasGcMsgSrc) {
      GcMsgSrc = other.GcMsgSrc;
    }
    if (other.HasGcDirIndexSource) {
      GcDirIndexSource = other.GcDirIndexSource;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          ClientSteamId = input.ReadFixed64();
          break;
        }
        case 16: {
          ClientSessionId = input.ReadInt32();
          break;
        }
        case 24: {
          SourceAppId = input.ReadUInt32();
          break;
        }
        case 81: {
          JobIdSource = input.ReadFixed64();
          break;
        }
        case 89: {
          JobIdTarget = input.ReadFixed64();
          break;
        }
        case 98: {
          TargetJobName = input.ReadString();
          break;
        }
        case 104: {
          Eresult = input.ReadInt32();
          break;
        }
        case 114: {
          ErrorMessage = input.ReadString();
          break;
        }
        case 120: {
          Ip = input.ReadUInt32();
          break;
        }
        case 1600: {
          GcMsgSrc = (global::GCProtoBufMsgSrc) input.ReadEnum();
          break;
        }
        case 1608: {
          GcDirIndexSource = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          ClientSteamId = input.ReadFixed64();
          break;
        }
        case 16: {
          ClientSessionId = input.ReadInt32();
          break;
        }
        case 24: {
          SourceAppId = input.ReadUInt32();
          break;
        }
        case 81: {
          JobIdSource = input.ReadFixed64();
          break;
        }
        case 89: {
          JobIdTarget = input.ReadFixed64();
          break;
        }
        case 98: {
          TargetJobName = input.ReadString();
          break;
        }
        case 104: {
          Eresult = input.ReadInt32();
          break;
        }
        case 114: {
          ErrorMessage = input.ReadString();
          break;
        }
        case 120: {
          Ip = input.ReadUInt32();
          break;
        }
        case 1600: {
          GcMsgSrc = (global::GCProtoBufMsgSrc) input.ReadEnum();
          break;
        }
        case 1608: {
          GcDirIndexSource = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CChinaAgreementSessions_StartAgreementSessionInGame_Request : pb::IMessage<CChinaAgreementSessions_StartAgreementSessionInGame_Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CChinaAgreementSessions_StartAgreementSessionInGame_Request> _parser = new pb::MessageParser<CChinaAgreementSessions_StartAgreementSessionInGame_Request>(() => new CChinaAgreementSessions_StartAgreementSessionInGame_Request());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CChinaAgreementSessions_StartAgreementSessionInGame_Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CChinaAgreementSessions_StartAgreementSessionInGame_Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CChinaAgreementSessions_StartAgreementSessionInGame_Request(CChinaAgreementSessions_StartAgreementSessionInGame_Request other) : this() {
    _hasBits0 = other._hasBits0;
    appid_ = other.appid_;
    steamid_ = other.steamid_;
    clientIpaddress_ = other.clientIpaddress_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CChinaAgreementSessions_StartAgreementSessionInGame_Request Clone() {
    return new CChinaAgreementSessions_StartAgreementSessionInGame_Request(this);
  }

  /// <summary>Field number for the "appid" field.</summary>
  public const int AppidFieldNumber = 1;
  private readonly static uint AppidDefaultValue = 0;

  private uint appid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Appid {
    get { if ((_hasBits0 & 1) != 0) { return appid_; } else { return AppidDefaultValue; } }
    set {
      _hasBits0 |= 1;
      appid_ = value;
    }
  }
  /// <summary>Gets whether the "appid" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAppid {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "appid" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAppid() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "steamid" field.</summary>
  public const int SteamidFieldNumber = 2;
  private readonly static ulong SteamidDefaultValue = 0UL;

  private ulong steamid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Steamid {
    get { if ((_hasBits0 & 2) != 0) { return steamid_; } else { return SteamidDefaultValue; } }
    set {
      _hasBits0 |= 2;
      steamid_ = value;
    }
  }
  /// <summary>Gets whether the "steamid" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSteamid {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "steamid" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSteamid() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "client_ipaddress" field.</summary>
  public const int ClientIpaddressFieldNumber = 3;
  private readonly static string ClientIpaddressDefaultValue = "";

  private string clientIpaddress_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientIpaddress {
    get { return clientIpaddress_ ?? ClientIpaddressDefaultValue; }
    set {
      clientIpaddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "client_ipaddress" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasClientIpaddress {
    get { return clientIpaddress_ != null; }
  }
  /// <summary>Clears the value of the "client_ipaddress" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearClientIpaddress() {
    clientIpaddress_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CChinaAgreementSessions_StartAgreementSessionInGame_Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CChinaAgreementSessions_StartAgreementSessionInGame_Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Appid != other.Appid) return false;
    if (Steamid != other.Steamid) return false;
    if (ClientIpaddress != other.ClientIpaddress) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasAppid) hash ^= Appid.GetHashCode();
    if (HasSteamid) hash ^= Steamid.GetHashCode();
    if (HasClientIpaddress) hash ^= ClientIpaddress.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasAppid) {
      output.WriteRawTag(8);
      output.WriteUInt32(Appid);
    }
    if (HasSteamid) {
      output.WriteRawTag(17);
      output.WriteFixed64(Steamid);
    }
    if (HasClientIpaddress) {
      output.WriteRawTag(26);
      output.WriteString(ClientIpaddress);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasAppid) {
      output.WriteRawTag(8);
      output.WriteUInt32(Appid);
    }
    if (HasSteamid) {
      output.WriteRawTag(17);
      output.WriteFixed64(Steamid);
    }
    if (HasClientIpaddress) {
      output.WriteRawTag(26);
      output.WriteString(ClientIpaddress);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasAppid) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Appid);
    }
    if (HasSteamid) {
      size += 1 + 8;
    }
    if (HasClientIpaddress) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientIpaddress);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CChinaAgreementSessions_StartAgreementSessionInGame_Request other) {
    if (other == null) {
      return;
    }
    if (other.HasAppid) {
      Appid = other.Appid;
    }
    if (other.HasSteamid) {
      Steamid = other.Steamid;
    }
    if (other.HasClientIpaddress) {
      ClientIpaddress = other.ClientIpaddress;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Appid = input.ReadUInt32();
          break;
        }
        case 17: {
          Steamid = input.ReadFixed64();
          break;
        }
        case 26: {
          ClientIpaddress = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Appid = input.ReadUInt32();
          break;
        }
        case 17: {
          Steamid = input.ReadFixed64();
          break;
        }
        case 26: {
          ClientIpaddress = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CChinaAgreementSessions_StartAgreementSessionInGame_Response : pb::IMessage<CChinaAgreementSessions_StartAgreementSessionInGame_Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CChinaAgreementSessions_StartAgreementSessionInGame_Response> _parser = new pb::MessageParser<CChinaAgreementSessions_StartAgreementSessionInGame_Response>(() => new CChinaAgreementSessions_StartAgreementSessionInGame_Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CChinaAgreementSessions_StartAgreementSessionInGame_Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CChinaAgreementSessions_StartAgreementSessionInGame_Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CChinaAgreementSessions_StartAgreementSessionInGame_Response(CChinaAgreementSessions_StartAgreementSessionInGame_Response other) : this() {
    agreementUrl_ = other.agreementUrl_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CChinaAgreementSessions_StartAgreementSessionInGame_Response Clone() {
    return new CChinaAgreementSessions_StartAgreementSessionInGame_Response(this);
  }

  /// <summary>Field number for the "agreement_url" field.</summary>
  public const int AgreementUrlFieldNumber = 1;
  private readonly static string AgreementUrlDefaultValue = "";

  private string agreementUrl_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AgreementUrl {
    get { return agreementUrl_ ?? AgreementUrlDefaultValue; }
    set {
      agreementUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "agreement_url" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAgreementUrl {
    get { return agreementUrl_ != null; }
  }
  /// <summary>Clears the value of the "agreement_url" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAgreementUrl() {
    agreementUrl_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CChinaAgreementSessions_StartAgreementSessionInGame_Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CChinaAgreementSessions_StartAgreementSessionInGame_Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AgreementUrl != other.AgreementUrl) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasAgreementUrl) hash ^= AgreementUrl.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasAgreementUrl) {
      output.WriteRawTag(10);
      output.WriteString(AgreementUrl);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasAgreementUrl) {
      output.WriteRawTag(10);
      output.WriteString(AgreementUrl);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasAgreementUrl) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AgreementUrl);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CChinaAgreementSessions_StartAgreementSessionInGame_Response other) {
    if (other == null) {
      return;
    }
    if (other.HasAgreementUrl) {
      AgreementUrl = other.AgreementUrl;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          AgreementUrl = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          AgreementUrl = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
