/* 
 * ModSharp
 * Copyright (C) 2023-2025 Kxnrl. All Rights Reserved.
 *
 * This file is part of ModSharp.
 * ModSharp is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * ModSharp is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ModSharp. If not, see <https://www.gnu.org/licenses/>.
 */

namespace Sharp.Shared.Enums;

public enum NetworkDisconnectionReason : uint
{
    Invalid                              = 0,
    Shutdown                             = 1,
    DisconnectByUser                     = 2,
    DisconnectByServer                   = 3,
    Lost                                 = 4,
    Overflow                             = 5,
    SteamBanned                          = 6,
    SteamInUse                           = 7,
    SteamTicket                          = 8,
    SteamLogon                           = 9,
    SteamAuthCancelled                   = 10,
    SteamAuthAlreadyUsed                 = 11,
    SteamAuthInvalid                     = 12,
    SteamVacBanState                     = 13,
    SteamLoggedInElsewhere               = 14,
    SteamVacCheckTimedOut                = 15,
    SteamDropped                         = 16,
    SteamOwnership                       = 17,
    ServerInfoOverflow                   = 18,
    TickMsgOverflow                      = 19,
    StringTableMsgOverflow               = 20,
    DeltaEntMsgOverflow                  = 21,
    TempEntMsgOverflow                   = 22,
    SoundsMsgOverflow                    = 23,
    SnapshotOverflow                     = 24,
    SnapshotError                        = 25,
    ReliableOverflow                     = 26,
    BadDeltaTick                         = 27,
    NoMoreSplits                         = 28,
    TimedOut                             = 29,
    Disconnected                         = 30,
    LeavingSplit                         = 31,
    DifferentClassTables                 = 32,
    BadRelayPassword                     = 33,
    BadSpectatorPassword                 = 34,
    HltvRestricted                       = 35,
    NoSpectators                         = 36,
    HltvUnavailable                      = 37,
    HltvStop                             = 38,
    Kicked                               = 39,
    BanAdded                             = 40,
    KickBanAdded                         = 41,
    HltvDirect                           = 42,
    PureServerClientExtra                = 43,
    PureServerMismatch                   = 44,
    UserCmd                              = 45,
    RejectedByGame                       = 46,
    MessageParseError                    = 47,
    InvalidMessageError                  = 48,
    BadServerPassword                    = 49,
    DirectConnectReservation             = 50,
    ConnectionFailure                    = 51,
    NoPeerGroupHandlers                  = 52,
    Reconnection                         = 53,
    LoopShutdown                         = 54,
    LoopDeactivate                       = 55,
    HostEndGame                          = 56,
    LoopLevelLoadActivate                = 57,
    CreateServerFailed                   = 58,
    Exiting                              = 59,
    RequestHostStateIdle                 = 60,
    RequestHostStateHltvRelay            = 61,
    ClientConsistencyFail                = 62,
    ClientUnableToCrcMap                 = 63,
    ClientNoMap                          = 64,
    ClientDifferentMap                   = 65,
    ServerRequiresSteam                  = 66,
    SteamDenyMisc                        = 67,
    SteamDenyBadAntiCheat                = 68,
    ServerShutdown                       = 69,
    ReplayIncompatible                   = 71,
    ConnectRequestTimedOut               = 72,
    ServerIncompatible                   = 73,
    LocalProblemManyRelays               = 74,
    LocalProblemHostedServerPrimaryRelay = 75,
    LocalProblemNetworkConfig            = 76,
    LocalProblemOther                    = 77,
    RemoteTimeout                        = 79,
    RemoteTimeoutConnecting              = 80,
    RemoteOther                          = 81,
    RemoteBadCrypt                       = 82,
    RemoteCertNotTrusted                 = 83,
    Unusual                              = 84,
    InternalError                        = 85,
    RejectBadChallenge                   = 128,
    RejectNoLobby                        = 129,
    RejectBackgroundMap                  = 130,
    RejectSinglePlayer                   = 131,
    RejectHiddenGame                     = 132,
    RejectLanRestrict                    = 133,
    RejectBadPassword                    = 134,
    RejectServerFull                     = 135,
    RejectInvalidReservation             = 136,
    RejectFailedChannel                  = 137,
    RejectConnectFromLobby               = 138,
    RejectReservedForLobby               = 139,
    RejectInvalidKeyLength               = 140,
    RejectOldProtocol                    = 141,
    RejectNewProtocol                    = 142,
    RejectInvalidConnection              = 143,
    RejectInvalidCertLen                 = 144,
    RejectInvalidSteamCertLen            = 145,
    RejectSteam                          = 146,
    RejectServerAuthDisabled             = 147,
    RejectServerCdKeyAuthInvalid         = 148,
    RejectBanned                         = 149,
    KickedTeamKilling                    = 150,
    KickedTkStart                        = 151,
    KickedUntrustedAccount               = 152,
    KickedConvictedAccount               = 153,
    KickedCompetitiveCooldown            = 154,
    KickedTeamHurting                    = 155,
    KickedHostageKilling                 = 156,
    KickedVotedOff                       = 157,
    KickedIdle                           = 158,
    KickedSuicide                        = 159,
    KickedNoSteamLogin                   = 160,
    KickedNoSteamTicket                  = 161,
    KickedInputAutomation                = 162,
    KickedVacNetAbnormalBehavior         = 163,
    KickedInsecureClient                 = 164,
};
