/* 
 * ModSharp
 * Copyright (C) 2023-2025 Kxnrl. All Rights Reserved.
 *
 * This file is part of ModSharp.
 * ModSharp is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * ModSharp is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ModSharp. If not, see <https://www.gnu.org/licenses/>.
 */

namespace Sharp.Shared.Enums;

// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo
public enum ProtobufNetMessageType : ushort
{
    /* CLC_Messages */
    clc_ClientInfo            = 20,
    clc_Move                  = 21,
    clc_VoiceData             = 22,
    clc_BaselineAck           = 23,
    clc_RespondCvarValue      = 25,
    clc_FileCRCCheck          = 26,
    clc_LoadingProgress       = 27,
    clc_SplitPlayerConnect    = 28,
    clc_SplitPlayerDisconnect = 30,
    clc_ServerStatus          = 31,
    clc_RequestPause          = 33,
    clc_CmdKeyValues          = 34,
    clc_RconServerDetails     = 35,
    clc_HltvReplay            = 36,
    clc_Diagnostic            = 37,

    /* SVC_Messages */
    svc_ServerInfo              = 40,
    svc_FlattenedSerializer     = 41,
    svc_ClassInfo               = 42,
    svc_SetPause                = 43,
    svc_CreateStringTable       = 44,
    svc_UpdateStringTable       = 45,
    svc_VoiceInit               = 46,
    svc_VoiceData               = 47,
    svc_Print                   = 48,
    svc_Sounds                  = 49,
    svc_SetView                 = 50,
    svc_ClearAllStringTables    = 51,
    svc_CmdKeyValues            = 52,
    svc_BSPDecal                = 53,
    svc_SplitScreen             = 54,
    svc_PacketEntities          = 55,
    svc_Prefetch                = 56,
    svc_Menu                    = 57,
    svc_GetCvarValue            = 58,
    svc_StopSound               = 59,
    svc_PeerList                = 60,
    svc_PacketReliable          = 61,
    svc_HLTVStatus              = 62,
    svc_ServerSteamID           = 63,
    svc_FullFrameSplit          = 70,
    svc_RconServerDetails       = 71,
    svc_UserMessage             = 72,
    svc_Broadcast_Command       = 74,
    svc_HltvFixupOperatorStatus = 75,
    svc_UserCmds                = 76,

    /* EBaseUserMessages */
    UM_AchievementEvent        = 101,
    UM_CloseCaption            = 102,
    UM_CloseCaptionDirect      = 103,
    UM_CurrentTimescale        = 104,
    UM_DesiredTimescale        = 105,
    UM_Fade                    = 106,
    UM_GameTitle               = 107,
    UM_HudMsg                  = 110,
    UM_HudText                 = 111,
    UM_ColoredText             = 113,
    UM_RequestState            = 114,
    UM_ResetHUD                = 115,
    UM_Rumble                  = 116,
    UM_SayText                 = 117,
    UM_SayText2                = 118,
    UM_SayTextChannel          = 119,
    UM_Shake                   = 120,
    UM_ShakeDir                = 121,
    UM_WaterShake              = 122,
    UM_TextMsg                 = 124,
    UM_ScreenTilt              = 125,
    UM_VoiceMask               = 128,
    UM_SendAudio               = 130,
    UM_ItemPickup              = 131,
    UM_AmmoDenied              = 132,
    UM_ShowMenu                = 134,
    UM_CreditsMsg              = 135,
    UM_CloseCaptionPlaceholder = 142,
    UM_CameraTransition        = 143,
    UM_AudioParameter          = 144,
    UM_ParticleManager         = 145,
    UM_HudError                = 146,
    UM_CustomGameEvent         = 148,
    UM_AnimGraphUpdate         = 149,
    UM_HapticsManagerPulse     = 150,
    UM_HapticsManagerEffect    = 151,
    UM_UpdateCssClasses        = 153,
    UM_ServerFrameTime         = 154,
    UM_LagCompensationError    = 155,
    UM_RequestDllStatus        = 156,
    UM_RequestUtilAction       = 157,
    UM_UtilActionResponse      = 158,
    UM_DllStatusResponse       = 159,
    UM_RequestInventory        = 160,
    UM_InventoryResponse       = 161,
    UM_RequestDiagnostic       = 162,
    UM_DiagnosticResponse      = 163,
    UM_ExtraUserData           = 164,
    UM_NotifyResponseFound     = 165,
    UM_PlayResponseConditional = 166,

    /* EBaseEntityMessages */
    EM_PlayJingle      = 136,
    EM_ScreenOverlay   = 137,
    EM_RemoveAllDecals = 138,
    EM_PropagateForce  = 139,
    EM_DoSpark         = 140,
    EM_FixAngle        = 141,

    /* ECstrike15UserMessages */
    CS_UM_VGUIMenu                     = 301,
    CS_UM_Geiger                       = 302,
    CS_UM_Train                        = 303,
    CS_UM_HudText                      = 304,
    CS_UM_SayText                      = 305,
    CS_UM_SayText2                     = 306,
    CS_UM_TextMsg                      = 307,
    CS_UM_HudMsg                       = 308,
    CS_UM_ResetHud                     = 309,
    CS_UM_GameTitle                    = 310,
    CS_UM_Shake                        = 312,
    CS_UM_Fade                         = 313,
    CS_UM_Rumble                       = 314,
    CS_UM_CloseCaption                 = 315,
    CS_UM_CloseCaptionDirect           = 316,
    CS_UM_SendAudio                    = 317,
    CS_UM_RawAudio                     = 318,
    CS_UM_VoiceMask                    = 319,
    CS_UM_RequestState                 = 320,
    CS_UM_Damage                       = 321,
    CS_UM_RadioText                    = 322,
    CS_UM_HintText                     = 323,
    CS_UM_KeyHintText                  = 324,
    CS_UM_ProcessSpottedEntityUpdate   = 325,
    CS_UM_ReloadEffect                 = 326,
    CS_UM_AdjustMoney                  = 327,
    CS_UM_UpdateTeamMoney              = 328,
    CS_UM_StopSpectatorMode            = 329,
    CS_UM_KillCam                      = 330,
    CS_UM_DesiredTimescale             = 331,
    CS_UM_CurrentTimescale             = 332,
    CS_UM_AchievementEvent             = 333,
    CS_UM_MatchEndConditions           = 334,
    CS_UM_DisconnectToLobby            = 335,
    CS_UM_PlayerStatsUpdate            = 336,
    CS_UM_ClientInfo                   = 339,
    CS_UM_XRankGet                     = 340,
    CS_UM_XRankUpd                     = 341,
    CS_UM_CallVoteFailed               = 345,
    CS_UM_VoteStart                    = 346,
    CS_UM_VotePass                     = 347,
    CS_UM_VoteFailed                   = 348,
    CS_UM_VoteSetup                    = 349,
    CS_UM_ServerRankRevealAll          = 350,
    CS_UM_SendLastKillerDamageToClient = 351,
    CS_UM_ServerRankUpdate             = 352,
    CS_UM_ItemPickup                   = 353,
    CS_UM_ShowMenu                     = 354,
    CS_UM_BarTime                      = 355,
    CS_UM_AmmoDenied                   = 356,
    CS_UM_MarkAchievement              = 357,
    CS_UM_MatchStatsUpdate             = 358,
    CS_UM_ItemDrop                     = 359,
    CS_UM_SendPlayerItemDrops          = 361,
    CS_UM_RoundBackupFilenames         = 362,
    CS_UM_SendPlayerItemFound          = 363,
    CS_UM_ReportHit                    = 364,
    CS_UM_XpUpdate                     = 365,
    CS_UM_QuestProgress                = 366,
    CS_UM_ScoreLeaderboardData         = 367,
    CS_UM_PlayerDecalDigitalSignature  = 368,
    CS_UM_WeaponSound                  = 369,
    CS_UM_UpdateScreenHealthBar        = 370,
    CS_UM_EntityOutlineHighlight       = 371,
    CS_UM_SSUI                         = 372,
    CS_UM_SurvivalStats                = 373,
    CS_UM_DisconnectToLobby2           = 374,
    CS_UM_EndOfMatchAllPlayersData     = 375,
    CS_UM_PostRoundDamageReport        = 376,
    CS_UM_RoundEndReportData           = 379,
    CS_UM_CurrentRoundOdds             = 380,
    CS_UM_DeepStats                    = 381,
    CS_UM_ShootInfo                    = 383,
    CS_UM_CounterStrafe                = 385,
    CS_UM_DamagePrediction             = 386,
    CS_UM_RecurringMissionSchema       = 387,

    /* EBaseGameEvents */
    GE_VDebugGameSessionIDEvent   = 200,
    GE_PlaceDecalEvent            = 201,
    GE_ClearWorldDecalsEvent      = 202,
    GE_ClearEntityDecalsEvent     = 203,
    GE_ClearDecalsForEntityEvent  = 204,
    GE_Source1LegacyGameEventList = 205,
    GE_Source1LegacyListenEvents  = 206,
    GE_Source1LegacyGameEvent     = 207,
    GE_SosStartSoundEvent         = 208,
    GE_SosStopSoundEvent          = 209,
    GE_SosSetSoundEventParams     = 210,
    GE_SosSetLibraryStackFields   = 211,
    GE_SosStopSoundEventHash      = 212,

    /* ECsgoGameEvents */
    GE_PlayerAnimEventId = 450,
    GE_RadioIconEventId  = 451,
    GE_FireBulletsId     = 452,

    /* ETEProtobufIds */
    TE_EffectDispatchId = 400,
    TE_ArmorRicochetId  = 401,
    TE_BeamEntPointId   = 402,
    TE_BeamEntsId       = 403,
    TE_BeamPointsId     = 404,
    TE_BeamRingId       = 405,
    TE_BubblesId        = 408,
    TE_BubbleTrailId    = 409,
    TE_DecalId          = 410,
    TE_WorldDecalId     = 411,
    TE_EnergySplashId   = 412,
    TE_FizzId           = 413,
    TE_ShatterSurfaceId = 414,
    TE_GlowSpriteId     = 415,
    TE_ImpactId         = 416,
    TE_MuzzleFlashId    = 417,
    TE_BloodStreamId    = 418,
    TE_ExplosionId      = 419,
    TE_DustId           = 420,
    TE_LargeFunnelId    = 421,
    TE_SparksId         = 422,
    TE_PhysicsPropId    = 423,
    TE_SmokeId          = 426,
}
